// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migrations;

namespace Migrations.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210112171255_FutureFlights")]
    partial class FutureFlights
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("Migrations.Models.Flights", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("adult")
                        .HasColumnType("INTEGER");

                    b.Property<string>("arrivalCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("arrivalCountry")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("arrivalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("departureCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("departureCountry")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("departureDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("price")
                        .HasColumnType("REAL");

                    b.Property<Guid>("userId")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Flights");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Flights");
                });

            modelBuilder.Entity("Migrations.Models.ListOfUserThings", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("arrayOfThings")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("userId")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("ListOfUserThings");
                });

            modelBuilder.Entity("Migrations.Models.Token", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("token")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Migrations.Models.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("passportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("surname")
                        .HasColumnType("TEXT");

                    b.Property<string>("userName")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Migrations.Models.EarlyFlight", b =>
                {
                    b.HasBaseType("Migrations.Models.Flights");

                    b.HasDiscriminator().HasValue("EarlyFlight");
                });

            modelBuilder.Entity("Migrations.Models.FutureFlight", b =>
                {
                    b.HasBaseType("Migrations.Models.Flights");

                    b.HasDiscriminator().HasValue("FutureFlight");
                });
#pragma warning restore 612, 618
        }
    }
}
